export const API = {
  SIGNUP: "/signup",
  SIGNIN: "/signin",
  CHECKTOKEN: "/token",
  MARKER: "/marker",
  ARCONTENT: "/arcontent",
  ARCONTENTDUOCCHON: "/arcontent/duocchon",
  LECTURE: "/lecture",
  HANHDONGKHOITAO: '/hanhdong/khoitao',
  HANHDONG: '/hanhdong',
  NOIDUNGARHANHDONG: '/arcontent/hanhdong',
  HANHDONGDOITUONG: '/hanhdong/doituong',
  ARCONTENTTHAT: '/arcontent/that',
  NOIDUNGTEXT: '/arcontent/text',
  NOIDUNG: '/arcontent/noidung',
  NEW: '/lecture/new',
  MARKER: '/lecture/marker',
  ADDMARKER: '/marker/add',
  DELETE: '/lecture/delete'
};
